# coding: utf-8

"""
    Scubawhere API Documentation

    This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

    OpenAPI spec version: 1.0.0
    Contact: bryan@scubawhere.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.session_api import SessionApi


class TestSessionApi(unittest.TestCase):
    """ SessionApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.session_api.SessionApi()

    def tearDown(self):
        pass

    def test_create_session(self):
        """
        Test case for create_session

        Create a new session
        """
        pass

    def test_delete_session(self):
        """
        Test case for delete_session

        Delete a session by ID
        """
        pass

    def test_edit_session(self):
        """
        Test case for edit_session

        Update a session by ID
        """
        pass

    def test_filter_sessions(self):
        """
        Test case for filter_sessions

        Retrieve all of tsessions that match a filter
        """
        pass

    def test_get_all_sessions(self):
        """
        Test case for get_all_sessions

        Retrieve all sessions including any deleted models
        """
        pass

    def test_get_all_with_trashed_sessions(self):
        """
        Test case for get_all_with_trashed_sessions

        Retrieve all sessions including any deleted models
        """
        pass

    def test_get_manifest(self):
        """
        Test case for get_manifest

        Retrieve the customer manifest for this session
        """
        pass

    def test_get_session(self):
        """
        Test case for get_session

        Retrieve a session by ID
        """
        pass

    def test_get_today_sessions(self):
        """
        Test case for get_today_sessions

        Retrieve all of todays sessions
        """
        pass

    def test_get_tommorow_sessions(self):
        """
        Test case for get_tommorow_sessions

        Retrieve all of tommorows sessions
        """
        pass


if __name__ == '__main__':
    unittest.main()
