# coding: utf-8

"""
    Scubawhere API Documentation

    This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

    OpenAPI spec version: 1.0.0
    Contact: bryan@scubawhere.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into model package
from .accommodation import Accommodation
from .addon import Addon
from .agent import Agent
from .base_price import BasePrice
from .boat import Boat
from .boatroom import Boatroom
from .booking import Booking
from .company import Company
from .country import Country
from .course import Course
from .currency import Currency
from .customer import Customer
from .date_range import DateRange
from .error_model import ErrorModel
from .inline_response_200 import InlineResponse200
from .inline_response_200_1 import InlineResponse2001
from .inline_response_200_10 import InlineResponse20010
from .inline_response_200_11 import InlineResponse20011
from .inline_response_200_12 import InlineResponse20012
from .inline_response_200_13 import InlineResponse20013
from .inline_response_200_14 import InlineResponse20014
from .inline_response_200_15 import InlineResponse20015
from .inline_response_200_16 import InlineResponse20016
from .inline_response_200_17 import InlineResponse20017
from .inline_response_200_18 import InlineResponse20018
from .inline_response_200_19 import InlineResponse20019
from .inline_response_200_2 import InlineResponse2002
from .inline_response_200_20 import InlineResponse20020
from .inline_response_200_21 import InlineResponse20021
from .inline_response_200_22 import InlineResponse20022
from .inline_response_200_23 import InlineResponse20023
from .inline_response_200_24 import InlineResponse20024
from .inline_response_200_25 import InlineResponse20025
from .inline_response_200_26 import InlineResponse20026
from .inline_response_200_27 import InlineResponse20027
from .inline_response_200_28 import InlineResponse20028
from .inline_response_200_29 import InlineResponse20029
from .inline_response_200_3 import InlineResponse2003
from .inline_response_200_30 import InlineResponse20030
from .inline_response_200_31 import InlineResponse20031
from .inline_response_200_32 import InlineResponse20032
from .inline_response_200_33 import InlineResponse20033
from .inline_response_200_34 import InlineResponse20034
from .inline_response_200_35 import InlineResponse20035
from .inline_response_200_36 import InlineResponse20036
from .inline_response_200_37 import InlineResponse20037
from .inline_response_200_38 import InlineResponse20038
from .inline_response_200_39 import InlineResponse20039
from .inline_response_200_4 import InlineResponse2004
from .inline_response_200_40 import InlineResponse20040
from .inline_response_200_41 import InlineResponse20041
from .inline_response_200_42 import InlineResponse20042
from .inline_response_200_42_utilisation import InlineResponse20042Utilisation
from .inline_response_200_42_utilisation_totals import InlineResponse20042UtilisationTotals
from .inline_response_200_43 import InlineResponse20043
from .inline_response_200_44 import InlineResponse20044
from .inline_response_200_45 import InlineResponse20045
from .inline_response_200_46 import InlineResponse20046
from .inline_response_200_47 import InlineResponse20047
from .inline_response_200_5 import InlineResponse2005
from .inline_response_200_6 import InlineResponse2006
from .inline_response_200_7 import InlineResponse2007
from .inline_response_200_8 import InlineResponse2008
from .inline_response_200_9 import InlineResponse2009
from .inline_response_201 import InlineResponse201
from .inline_response_201_1 import InlineResponse2011
from .inline_response_201_2 import InlineResponse2012
from .inline_response_201_3 import InlineResponse2013
from .inline_response_201_4 import InlineResponse2014
from .inline_response_201_5 import InlineResponse2015
from .location import Location
from .package import Package
from .payment import Payment
from .payment_gateway import PaymentGateway
from .pickup import Pickup
from .refund import Refund
from .report_entry import ReportEntry
from .report_entry_total import ReportEntryTotal
from .schedule import Schedule
from .session import Session
from .tag import Tag
from .ticket import Ticket
from .timetable import Timetable
from .training import Training
from .training_session import TrainingSession
from .training_session_manifest import TrainingSessionManifest
from .training_session_manifest_capacity import TrainingSessionManifestCapacity
from .trip import Trip
