# coding: utf-8

"""
    Scubawhere API Documentation

    This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

    OpenAPI spec version: 1.0.0
    Contact: bryan@scubawhere.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse20042UtilisationTotals(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, assigned=None, unassigned=None, capacity=None, relations=None):
        """
        InlineResponse20042UtilisationTotals - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'assigned': 'int',
            'unassigned': 'int',
            'capacity': 'int',
            'relations': 'list[int]'
        }

        self.attribute_map = {
            'assigned': 'assigned',
            'unassigned': 'unassigned',
            'capacity': 'capacity',
            'relations': 'relations'
        }

        self._assigned = assigned
        self._unassigned = unassigned
        self._capacity = capacity
        self._relations = relations

    @property
    def assigned(self):
        """
        Gets the assigned of this InlineResponse20042UtilisationTotals.


        :return: The assigned of this InlineResponse20042UtilisationTotals.
        :rtype: int
        """
        return self._assigned

    @assigned.setter
    def assigned(self, assigned):
        """
        Sets the assigned of this InlineResponse20042UtilisationTotals.


        :param assigned: The assigned of this InlineResponse20042UtilisationTotals.
        :type: int
        """

        self._assigned = assigned

    @property
    def unassigned(self):
        """
        Gets the unassigned of this InlineResponse20042UtilisationTotals.


        :return: The unassigned of this InlineResponse20042UtilisationTotals.
        :rtype: int
        """
        return self._unassigned

    @unassigned.setter
    def unassigned(self, unassigned):
        """
        Sets the unassigned of this InlineResponse20042UtilisationTotals.


        :param unassigned: The unassigned of this InlineResponse20042UtilisationTotals.
        :type: int
        """

        self._unassigned = unassigned

    @property
    def capacity(self):
        """
        Gets the capacity of this InlineResponse20042UtilisationTotals.


        :return: The capacity of this InlineResponse20042UtilisationTotals.
        :rtype: int
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """
        Sets the capacity of this InlineResponse20042UtilisationTotals.


        :param capacity: The capacity of this InlineResponse20042UtilisationTotals.
        :type: int
        """

        self._capacity = capacity

    @property
    def relations(self):
        """
        Gets the relations of this InlineResponse20042UtilisationTotals.


        :return: The relations of this InlineResponse20042UtilisationTotals.
        :rtype: list[int]
        """
        return self._relations

    @relations.setter
    def relations(self, relations):
        """
        Sets the relations of this InlineResponse20042UtilisationTotals.


        :param relations: The relations of this InlineResponse20042UtilisationTotals.
        :type: list[int]
        """

        self._relations = relations

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
