# coding: utf-8

"""
    Scubawhere API Documentation

    This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

    OpenAPI spec version: 1.0.0
    Contact: bryan@scubawhere.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse20025(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, status=None, date=None, pick_ups=None):
        """
        InlineResponse20025 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'status': 'str',
            'date': 'date',
            'pick_ups': 'list[Pickup]'
        }

        self.attribute_map = {
            'status': 'status',
            'date': 'date',
            'pick_ups': 'pick_ups'
        }

        self._status = status
        self._date = date
        self._pick_ups = pick_ups

    @property
    def status(self):
        """
        Gets the status of this InlineResponse20025.


        :return: The status of this InlineResponse20025.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this InlineResponse20025.


        :param status: The status of this InlineResponse20025.
        :type: str
        """

        self._status = status

    @property
    def date(self):
        """
        Gets the date of this InlineResponse20025.


        :return: The date of this InlineResponse20025.
        :rtype: date
        """
        return self._date

    @date.setter
    def date(self, date):
        """
        Sets the date of this InlineResponse20025.


        :param date: The date of this InlineResponse20025.
        :type: date
        """

        self._date = date

    @property
    def pick_ups(self):
        """
        Gets the pick_ups of this InlineResponse20025.


        :return: The pick_ups of this InlineResponse20025.
        :rtype: list[Pickup]
        """
        return self._pick_ups

    @pick_ups.setter
    def pick_ups(self, pick_ups):
        """
        Sets the pick_ups of this InlineResponse20025.


        :param pick_ups: The pick_ups of this InlineResponse20025.
        :type: list[Pickup]
        """

        self._pick_ups = pick_ups

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
