# coding: utf-8

"""
    Scubawhere API Documentation

    This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

    OpenAPI spec version: 1.0.0
    Contact: bryan@scubawhere.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class Package(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, name=None, description=None, available_from=None, available_until=None, decimal_price=None, trips=None, courses=None, accommodations=None):
        """
        Package - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'name': 'str',
            'description': 'str',
            'available_from': 'date',
            'available_until': 'date',
            'decimal_price': 'str',
            'trips': 'list[Ticket]',
            'courses': 'list[Course]',
            'accommodations': 'list[Accommodation]'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'available_from': 'available_from',
            'available_until': 'available_until',
            'decimal_price': 'decimal_price',
            'trips': 'trips',
            'courses': 'courses',
            'accommodations': 'accommodations'
        }

        self._id = id
        self._name = name
        self._description = description
        self._available_from = available_from
        self._available_until = available_until
        self._decimal_price = decimal_price
        self._trips = trips
        self._courses = courses
        self._accommodations = accommodations

    @property
    def id(self):
        """
        Gets the id of this Package.


        :return: The id of this Package.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Package.


        :param id: The id of this Package.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this Package.


        :return: The name of this Package.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Package.


        :param name: The name of this Package.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this Package.


        :return: The description of this Package.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Package.


        :param description: The description of this Package.
        :type: str
        """

        self._description = description

    @property
    def available_from(self):
        """
        Gets the available_from of this Package.


        :return: The available_from of this Package.
        :rtype: date
        """
        return self._available_from

    @available_from.setter
    def available_from(self, available_from):
        """
        Sets the available_from of this Package.


        :param available_from: The available_from of this Package.
        :type: date
        """

        self._available_from = available_from

    @property
    def available_until(self):
        """
        Gets the available_until of this Package.


        :return: The available_until of this Package.
        :rtype: date
        """
        return self._available_until

    @available_until.setter
    def available_until(self, available_until):
        """
        Sets the available_until of this Package.


        :param available_until: The available_until of this Package.
        :type: date
        """

        self._available_until = available_until

    @property
    def decimal_price(self):
        """
        Gets the decimal_price of this Package.


        :return: The decimal_price of this Package.
        :rtype: str
        """
        return self._decimal_price

    @decimal_price.setter
    def decimal_price(self, decimal_price):
        """
        Sets the decimal_price of this Package.


        :param decimal_price: The decimal_price of this Package.
        :type: str
        """

        self._decimal_price = decimal_price

    @property
    def trips(self):
        """
        Gets the trips of this Package.


        :return: The trips of this Package.
        :rtype: list[Ticket]
        """
        return self._trips

    @trips.setter
    def trips(self, trips):
        """
        Sets the trips of this Package.


        :param trips: The trips of this Package.
        :type: list[Ticket]
        """

        self._trips = trips

    @property
    def courses(self):
        """
        Gets the courses of this Package.


        :return: The courses of this Package.
        :rtype: list[Course]
        """
        return self._courses

    @courses.setter
    def courses(self, courses):
        """
        Sets the courses of this Package.


        :param courses: The courses of this Package.
        :type: list[Course]
        """

        self._courses = courses

    @property
    def accommodations(self):
        """
        Gets the accommodations of this Package.


        :return: The accommodations of this Package.
        :rtype: list[Accommodation]
        """
        return self._accommodations

    @accommodations.setter
    def accommodations(self, accommodations):
        """
        Sets the accommodations of this Package.


        :param accommodations: The accommodations of this Package.
        :type: list[Accommodation]
        """

        self._accommodations = accommodations

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
