# coding: utf-8

"""
    Scubawhere API Documentation

    This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

    OpenAPI spec version: 1.0.0
    Contact: bryan@scubawhere.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class TrainingSession(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, start=None, schedule_id=None, capacity=None, _class=None):
        """
        TrainingSession - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'start': 'date',
            'schedule_id': 'int',
            'capacity': 'int',
            '_class': 'Training'
        }

        self.attribute_map = {
            'id': 'id',
            'start': 'start',
            'schedule_id': 'schedule_id',
            'capacity': 'capacity',
            '_class': 'class'
        }

        self._id = id
        self._start = start
        self._schedule_id = schedule_id
        self._capacity = capacity
        self.__class = _class

    @property
    def id(self):
        """
        Gets the id of this TrainingSession.


        :return: The id of this TrainingSession.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TrainingSession.


        :param id: The id of this TrainingSession.
        :type: int
        """

        self._id = id

    @property
    def start(self):
        """
        Gets the start of this TrainingSession.


        :return: The start of this TrainingSession.
        :rtype: date
        """
        return self._start

    @start.setter
    def start(self, start):
        """
        Sets the start of this TrainingSession.


        :param start: The start of this TrainingSession.
        :type: date
        """

        self._start = start

    @property
    def schedule_id(self):
        """
        Gets the schedule_id of this TrainingSession.


        :return: The schedule_id of this TrainingSession.
        :rtype: int
        """
        return self._schedule_id

    @schedule_id.setter
    def schedule_id(self, schedule_id):
        """
        Sets the schedule_id of this TrainingSession.


        :param schedule_id: The schedule_id of this TrainingSession.
        :type: int
        """

        self._schedule_id = schedule_id

    @property
    def capacity(self):
        """
        Gets the capacity of this TrainingSession.


        :return: The capacity of this TrainingSession.
        :rtype: int
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """
        Sets the capacity of this TrainingSession.


        :param capacity: The capacity of this TrainingSession.
        :type: int
        """

        self._capacity = capacity

    @property
    def _class(self):
        """
        Gets the _class of this TrainingSession.


        :return: The _class of this TrainingSession.
        :rtype: Training
        """
        return self.__class

    @_class.setter
    def _class(self, _class):
        """
        Sets the _class of this TrainingSession.


        :param _class: The _class of this TrainingSession.
        :type: Training
        """

        self.__class = _class

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
